export const recentShopsFile = [
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/gears-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/dishes-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/healthcare-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/brush-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
];

export let allFilteredShops: any = [];

export const setAllFilteredShops = (arr: any) => {
    allFilteredShops = [...arr];
};

export const allShops = [
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/gears-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի 2",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/dishes-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի 2",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/healthcare-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի 3",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/brush-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի 3",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի 3",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
    {
        categoryIcon: require("../../Assets/shopping-bag-icon.svg") as string,
        brandLogo: require("../../Assets/brand-logo.svg") as string,
        shopName: "Ռոդենի",
        shopInstaName: "rodenishop_am",
        shopDescription: "Եղիր այն մեկը, ումով կհիանան",
    },
];
